import {FastifyInstance} from 'fastify'; import {z} from 'zod'; import {prisma} from '../lib/prisma'; import {getVideoProvider} from '../providers';
const input=z.object({personName:z.string().min(2).max(120),deathDate:z.string(),relationship:z.enum(['relative','friend','public_figure','historical','other']),imageUrl:z.string().url(),message:z.string().min(1).max(500),sceneType:z.enum(['calm','mysterious','era','monochrome','cemetery']),duration:z.union([z.literal(15),z.literal(30)]),voiceMode:z.enum(['screen_voice','voice','both']),privacy:z.enum(['public','unlisted','private']).default('unlisted')});
const code=()=>`LQ-${Math.random().toString(36).slice(2,8).toUpperCase()}`;
export async function requestRoutes(app:FastifyInstance){
 app.post('/api/requests',async(req,reply)=>{const p=input.safeParse(req.body);if(!p.success)return reply.code(400).send({error:'تحقق من البيانات المدخلة'}); const d=new Date(p.data.deathDate);if(Number.isNaN(d.getTime()))return reply.code(400).send({error:'تاريخ الوفاة غير صالح'}); const ap=new Date(Date.now()+24*60*60*1000); ap.setHours(20,30,0,0); const r=await prisma.memorialRequest.create({data:{...p.data,deathDate:d,requestCode:code(),appointmentDate:ap,appointmentTime:'20:30',voiceMode:p.data.voiceMode as any,privacy:p.data.privacy as any}});return {id:r.id,requestCode:r.requestCode,appointmentDate:r.appointmentDate,appointmentTime:r.appointmentTime}});
 app.get('/api/requests/:id',async(req,reply)=>{const r=await prisma.memorialRequest.findUnique({where:{id:(req.params as any).id}});if(!r)return reply.code(404).send({error:'الطلب غير موجود'});if(r.privacy==='private')return reply.code(403).send({error:'هذه الذكرى خاصة'});return r});
 app.get('/api/requests/:id/status',async(req,reply)=>{const r=await prisma.memorialRequest.findUnique({where:{id:(req.params as any).id},select:{status:true,videoUrl:true,requestCode:true,appointmentDate:true,appointmentTime:true}});if(!r)return reply.code(404).send({error:'الطلب غير موجود'});return r});
 app.post('/api/requests/:id/generate',async(req,reply)=>{const r=await prisma.memorialRequest.findUnique({where:{id:(req.params as any).id}});if(!r)return reply.code(404).send({error:'الطلب غير موجود'}); if(r.status==='ready')return r; const provider=getVideoProvider(); const job=await provider.create({imageUrl:r.imageUrl,prompt:r.message,duration:r.duration,sceneType:r.sceneType,message:r.message,voiceMode:r.voiceMode}); const u=await prisma.memorialRequest.update({where:{id:r.id},data:{status:'processing',providerJobId:job.providerJobId,providerName:process.env.VIDEO_PROVIDER||'mock'}}); if((process.env.VIDEO_PROVIDER||'mock')==='mock')setTimeout(async()=>{const done=await provider.get(job.providerJobId); if(done.status==='ready')await prisma.memorialRequest.update({where:{id:r.id},data:{status:'ready',videoUrl:done.videoUrl}})},9000); return {status:u.status,providerJobId:job.providerJobId}});
 app.get('/api/search',async(req)=>{const q=String((req.query as any).q||'').trim();if(!q)return {results:[]};const results=await prisma.memorialRequest.findMany({where:{privacy:'public',personName:{contains:q}},orderBy:{createdAt:'desc'},take:20,select:{id:true,personName:true,deathDate:true,imageUrl:true,requestCode:true}});return {results}});
}
