'use client';
import {useMemo,useState} from 'react'; import {useRouter} from 'next/navigation'; import Atmosphere from '../../components/Atmosphere'; import TopBar from '../../components/TopBar'; import Signature from '../../components/Signature';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:4000';
type Form={personName:string;deathDate:string;relationship:string;imageUrl:string;message:string;sceneType:string;duration:number;voiceMode:string;privacy:string};
const examples=['ذكراك لا تزال معنا.','بعض الأشخاص يغيبون عن أعيننا ولا يغيبون عن ذاكرتنا.','لو كان بإمكاني أن أقول لك شيئًا واحدًا...'];
export default function Create(){const router=useRouter();const [step,setStep]=useState(1);const [busy,setBusy]=useState(false);const [err,setErr]=useState('');const [form,setForm]=useState<Form>({personName:'',deathDate:'',relationship:'relative',imageUrl:'',message:'',sceneType:'mysterious',duration:30,voiceMode:'both',privacy:'unlisted'});const update=(x:Partial<Form>)=>setForm(v=>({...v,...x}));const valid=useMemo(()=>step===1?form.personName&&form.deathDate:step===2?!!form.imageUrl:step===3?form.message.length>0&&form.message.length<=500:true,[step,form]);
async function upload(file:File){setErr('');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){setErr('JPG / PNG / WEBP حتى 8MB فقط');return}const fd=new FormData();fd.append('file',file);setBusy(true);try{const r=await fetch(`${API}/api/uploads/image`,{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error);update({imageUrl:d.url})}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
async function submit(){setBusy(true);setErr('');try{const r=await fetch(`${API}/api/requests`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error);router.push(`/create/processing?id=${d.id}`)}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
return <main className="shell"><TopBar/><Atmosphere/><Signature/><section className="wizard"><div className="wizard-card"><div className="steps">{['البيانات','الصورة','الرسالة','التأكيد'].map((s,i)=><div className={`step ${step===i+1?'active':''} ${step>i+1?'done':''}`} key={s}>0{i+1} {s}</div>)}</div>{step===1&&<><h1 className="form-title">من تريد أن تلتقي؟</h1><p className="sub">ابدأ من الاسم والتاريخ، واترك الباقي للذاكرة.</p><div className="field"><label>اسم الشخص المتوفى</label><input className="input" value={form.personName} onChange={e=>update({personName:e.target.value})} placeholder="مثال: أحمد..."/></div><div className="field"><label>تاريخ الوفاة</label><input type="date" className="input" value={form.deathDate} onChange={e=>update({deathDate:e.target.value})}/></div><div className="field"><label>صلة الشخص بك</label><select className="select" value={form.relationship} onChange={e=>update({relationship:e.target.value})}><option value="relative">قريب</option><option value="friend">صديق</option><option value="public_figure">شخصية عامة</option><option value="historical">شخصية تاريخية</option><option value="other">أخرى</option></select></div></>}
{step===2&&<><h1 className="form-title">أضف صورة الشخص</h1><p className="sub">اختر صورة واضحة؛ ستُستخدم كمرجع بصري للمشهد.</p><label className="drop">{form.imageUrl?<img src={form.imageUrl} className="preview" alt="معاينة"/>:<span>اسحب الصورة هنا<br/>أو اضغط لاختيارها<br/><small>JPG / PNG / WEBP · 8MB</small></span>}<input type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>e.target.files&&upload(e.target.files[0])}/></label>{form.imageUrl&&<button className="ghost" style={{marginTop:10}} onClick={()=>update({imageUrl:''})}>حذف الصورة واستبدالها</button>}</>}
{step===3&&<><h1 className="form-title">ماذا تريد أن تقول له؟</h1><p className="sub">اكتب رسالة، ذكرى، دعاء، أو حكمة تريد ظهورها في المشهد.</p><textarea className="textarea" maxLength={500} value={form.message} onChange={e=>update({message:e.target.value})} placeholder="اكتب رسالتك هنا..."/><div className="counter">{form.message.length} / 500</div><div style={{marginTop:20}}><small style={{color:'#777'}}>أمثلة — اضغط لإدراجها:</small><div className="choices" style={{gridTemplateColumns:'1fr'}}>{examples.map(x=><button className="choice" key={x} onClick={()=>update({message:x})}>{x}</button>)}</div></div></>}
{step===4&&<><h1 className="form-title">هل كل شيء صحيح؟</h1><p className="sub">راجع تفاصيل اللقاء قبل إرسال الطلب.</p><div className="review"><img src={form.imageUrl} alt="الصورة"/><dl><dt>الاسم</dt><dd>{form.personName}</dd><dt>التاريخ</dt><dd>{form.deathDate}</dd><dt>المشهد</dt><dd><SceneName v={form.sceneType}/></dd><dt>المدة</dt><dd>{form.duration} ثانية</dd><dt>الرسالة</dt><dd>{form.message}</dd></dl></div><div className="field" style={{marginTop:30}}><label>نوع المشهد</label><div className="choices">{[['calm','تذكاري هادئ'],['mysterious','سينمائي غامض'],['era','من زمن الشخص'],['monochrome','أبيض وأسود'],['cemetery','مقبرة ليلية']].map(([v,n])=><button type="button" className={`choice ${form.sceneType===v?'active':''}`} key={v} onClick={()=>update({sceneType:v})}>{n}</button>)}</div></div><div className="field"><label>مدة الفيديو</label><div className="choices"><button className={`choice ${form.duration===15?'active':''}`} onClick={()=>update({duration:15})}>15 ثانية</button><button className={`choice ${form.duration===30?'active':''}`} onClick={()=>update({duration:30})}>30 ثانية</button></div></div><div className="field"><label>نمط الرسالة</label><div className="choices"><button className={`choice ${form.voiceMode==='screen_voice'?'active':''}`} onClick={()=>update({voiceMode:'screen_voice'})}>رسالة على الشاشة</button><button className={`choice ${form.voiceMode==='voice'?'active':''}`} onClick={()=>update({voiceMode:'voice'})}>صوت راوي</button><button className={`choice ${form.voiceMode==='both'?'active':''}`} onClick={()=>update({voiceMode:'both'})}>الاثنان معًا</button></div></div><div className="field"><label>خصوصية الذكرى</label><div className="choices"><button className={`choice ${form.privacy==='public'?'active':''}`} onClick={()=>update({privacy:'public'})}>Public · عامة</button><button className={`choice ${form.privacy==='unlisted'?'active':''}`} onClick={()=>update({privacy:'unlisted'})}>Unlisted · بالرابط</button><button className={`choice ${form.privacy==='private'?'active':''}`} onClick={()=>update({privacy:'private'})}>Private · خاصة</button></div></div><div className="warning">هذه تجربة فنية وتذكارية. أي صورة أو صوت أو فيديو مولّد هو إعادة تخيل رقمية، وليس تسجيلًا حقيقيًا أو تواصلًا مع الشخص المتوفى.</div></>}
{err&&<div className="warning">{err}</div>}<div className="actions">{step>1?<button className="ghost" onClick={()=>setStep(step-1)}>رجوع</button>:<span/>}{step<4?<button className="primary" disabled={!valid||busy} onClick={()=>setStep(step+1)}>{busy?'جارٍ...':'التالي'}</button>:<button className="primary" disabled={busy} onClick={submit}>{busy?'جارٍ إرسال الطلب...':'إرسال طلب اللقاء'}</button>}</div></div></section></main>}
function SceneName({v}:{v:string}){return <>{({'calm':'تذكاري هادئ','mysterious':'سينمائي غامض','era':'من زمن الشخص','monochrome':'أبيض وأسود','cemetery':'مقبرة ليلية'} as any)[v]}</>}
